module.exports = {
    mode: "jit",
    content: ["./src/**/*.{md,html}"],
    plugins: [require("@tailwindcss/typography")],
    darkmode: true,

    theme: {
        colors: {
            dark0: "#7f897d",
            dark1: "#232a2f",
            dark: "#2b3339",
            dark2: "#323c41",
            light0: "#a4ad9e",
            light1: "#f9f4e2",
            light: "#fff9e8",
            light2: "#f7f4e0",
            accent: "#93b259",

            base00: "#2b3339",
            base01: "#323c41",
            base02: "#3a454a",
            base03: "#868d80",
            base04: "#d3c6aa",
            base05: "#d3c6aa",
            base06: "#e9e8d2",
            base07: "#fff9e8",
            base08: "#e67e80",
            base09: "#e69875",
            base0A: "#dbbc7f",
            base0B: "#a7c080",
            base0C: "#83c092",
            base0D: "#7fbbb3",
            base0E: "#d699b6",
            base0F: "#93b259",
        },
        extend: {
            typography: ({ theme }) => ({
                DEFAULT: {
                    css: {
                        "font-size": "14pt",
                        "--tw-prose-body": theme("colors.dark"),
                        "--tw-prose-headings": theme("colors.dark"),
                        "--tw-prose-lead": theme("colors.dark"),
                        "--tw-prose-links": theme("colors.accent"),
                        "--tw-prose-bold": theme("colors.dark"),
                        "--tw-prose-counters": theme("colors.dark"),
                        "--tw-prose-bullets": theme("colors.light0"),
                        "--tw-prose-hr": theme("colors.light2"),
                        "--tw-prose-quotes": theme("colors.light0"),
                        "--tw-prose-quote-borders": theme("colors.light2"),
                        "--tw-prose-captions": theme("colors.light0"),
                        "--tw-prose-code": theme("colors.dark"),
                        "--tw-prose-pre-code": theme("colors.dark"),
                        "--tw-prose-pre-bg": theme("colors.light2"),
                        "--tw-prose-th-borders": theme("colors.light2"),
                        "--tw-prose-td-borders": theme("colors.light2"),
                        "--tw-prose-invert-body": theme("colors.light"),
                        "--tw-prose-invert-headings": theme("colors.light"),
                        "--tw-prose-invert-lead": theme("colors.light"),
                        "--tw-prose-invert-links": theme("colors.accent"),
                        "--tw-prose-invert-bold": theme("colors.light"),
                        "--tw-prose-invert-counters": theme("colors.light"),
                        "--tw-prose-invert-bullets": theme("colors.dark0"),
                        "--tw-prose-invert-hr": theme("colors.dark2"),
                        "--tw-prose-invert-quotes": theme("colors.dark0"),
                        "--tw-prose-invert-quote-borders": theme("colors.dark2"),
                        "--tw-prose-invert-captions": theme("colors.dark0"),
                        "--tw-prose-invert-code": theme("colors.light"),
                        "--tw-prose-invert-pre-code": theme("colors.light"),
                        "--tw-prose-invert-pre-bg": theme("colors.dark2"),
                        "--tw-prose-invert-th-borders": theme("colors.dark2"),
                        "--tw-prose-invert-td-borders": theme("colors.dark2"),
                    },
                },
            }),
        },
    },
};
